workdir="2.workqueues"

python $workdir/new_task.py 1.............
python $workdir/new_task.py 2..
python $workdir/new_task.py 3...........
python $workdir/new_task.py 4...
python $workdir/new_task.py 5...........
python $workdir/new_task.py 6..
python $workdir/new_task.py 7..
python $workdir/new_task.py 8.............
